"""Haskell / cabal backend -> declpkg-workspace.cabal (build-depends)"""

from __future__ import annotations

from .base import Backend, Package


def _constraint(pkg: Package) -> str:
    if not pkg.version:
        return pkg.name
    if pkg.version[0] in "<>=^":
        return f"{pkg.name} {pkg.version}"
    return f"{pkg.name} =={pkg.version}"


class CabalBackend(Backend):
    ecosystem = "cabal"
    native_file = "declpkg-workspace.cabal"

    def install_cmd(self, pkg: Package) -> list[str]:
        # Only a bare version can be an exact `pkg-x.y.z` install target; a
        # constraint (">=2.2 && <2.3") is honoured via the generated .cabal
        # file, so the imperative command just names the package.
        if pkg.version and pkg.version[0] not in "<>=^ ":
            return ["cabal", "install", "--lib", f"{pkg.name}-{pkg.version}"]
        return ["cabal", "install", "--lib", pkg.name]

    def remove_cmd(self, pkg: Package) -> list[str]:
        return ["cabal", "install", "--lib", pkg.name, "--disable"]

    def render_native(self, pkgs: list[Package]) -> str:
        deps = ",\n                 ".join(_constraint(p) for p in self._sorted(pkgs))
        return (
            "-- generated by declpkg -- do not edit by hand\n"
            "cabal-version:      2.4\n"
            "name:               declpkg-workspace\n"
            "version:            0.0.0\n\n"
            "library\n"
            f"    build-depends:   {deps}\n"
        )
