"""Rust / cargo backend -> Cargo.toml ([dependencies])"""

from __future__ import annotations

from .base import Backend, Package


def _dep_line(pkg: Package) -> str:
    if pkg.source:
        ver = f', version = "{pkg.version}"' if pkg.version else ""
        return f'{pkg.name} = {{ git = "{pkg.source}"{ver} }}'
    return f'{pkg.name} = "{pkg.version or "*"}"'


class CargoBackend(Backend):
    ecosystem = "cargo"
    native_file = "Cargo.toml"

    def install_cmd(self, pkg: Package) -> list[str]:
        ref = f"{pkg.name}@{pkg.version}" if pkg.version else pkg.name
        cmd = ["cargo", "add", ref]
        if pkg.source:
            cmd = ["cargo", "add", pkg.name, "--git", pkg.source]
        return cmd

    def remove_cmd(self, pkg: Package) -> list[str]:
        return ["cargo", "remove", pkg.name]

    def render_native(self, pkgs: list[Package]) -> str:
        lines = [
            "# generated by declpkg -- do not edit by hand",
            "[package]",
            'name = "declpkg-workspace"',
            'version = "0.0.0"',
            'edition = "2021"',
            "",
            "[dependencies]",
        ]
        lines += [_dep_line(p) for p in self._sorted(pkgs)]
        return "\n".join(lines) + "\n"
