"""Lean / lake backend -> lakefile.toml ([[require]])"""

from __future__ import annotations

from .base import Backend, Package


class LakeBackend(Backend):
    ecosystem = "lake"
    native_file = "lakefile.toml"

    def install_cmd(self, pkg: Package) -> list[str]:
        return ["lake", "update", pkg.name]

    def remove_cmd(self, pkg: Package) -> list[str]:
        # lake has no direct remove; regenerating the lakefile is the
        # declarative path. We still emit an intent command for the plan.
        return ["lake", "update", pkg.name, "--no-fetch"]

    def render_native(self, pkgs: list[Package]) -> str:
        lines = [
            "# generated by declpkg -- do not edit by hand",
            'name = "declpkg-workspace"',
            'defaultTargets = ["DeclpkgWorkspace"]',
            "",
        ]
        for p in self._sorted(pkgs):
            lines.append("[[require]]")
            lines.append(f'name = "{p.name}"')
            if p.source:
                lines.append(f'git = "{p.source}"')
            if p.version:
                # for git deps lake uses `rev`; for registry deps `version`
                key = "rev" if p.source else "version"
                lines.append(f'{key} = "{p.version}"')
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"
