"""Node / npm backend -> package.json (dependencies)"""

from __future__ import annotations

import json

from .base import Backend, Package


class NpmBackend(Backend):
    ecosystem = "npm"
    native_file = "package.json"

    def install_cmd(self, pkg: Package) -> list[str]:
        ref = f"{pkg.name}@{pkg.version}" if pkg.version else pkg.name
        return ["npm", "install", ref]

    def remove_cmd(self, pkg: Package) -> list[str]:
        return ["npm", "uninstall", pkg.name]

    def render_native(self, pkgs: list[Package]) -> str:
        deps = {p.name: (p.version or "latest") for p in self._sorted(pkgs)}
        doc = {
            "//": "generated by declpkg -- do not edit by hand",
            "name": "declpkg-workspace",
            "private": True,
            "dependencies": deps,
        }
        return json.dumps(doc, indent=2, sort_keys=True) + "\n"
