"""Python / pip backend -> requirements.txt"""

from __future__ import annotations

from .base import Backend, Package

_OPS = ("=", "<", ">", "!", "~", "@")


def _spec(pkg: Package) -> str:
    if not pkg.version:
        return pkg.name
    # Bare version like "1.2.3" pins exactly; anything with an operator
    # (>=, <, ==, ~=, ...) is passed through as a constraint.
    if pkg.version[0] in _OPS or "," in pkg.version:
        return f"{pkg.name}{pkg.version}"
    return f"{pkg.name}=={pkg.version}"


class PipBackend(Backend):
    ecosystem = "pip"
    native_file = "requirements.txt"

    def install_cmd(self, pkg: Package) -> list[str]:
        return ["pip", "install", _spec(pkg)]

    def remove_cmd(self, pkg: Package) -> list[str]:
        return ["pip", "uninstall", "-y", pkg.name]

    def render_native(self, pkgs: list[Package]) -> str:
        lines = ["# generated by declpkg -- do not edit by hand"]
        lines += [_spec(p) for p in self._sorted(pkgs)]
        return "\n".join(lines) + "\n"
